### ISSUE TITLE
Konsultasi Judul

### ISSUE THREAD

**Issue by bimprakosoo** [alola007/sa-project#1]
Pak, mau tanya kalau kami ganti judul project menjadi solving magic square 3x3 apa boleh ?
puzzlenya seperti ini pak : https://en.wikipedia.org/wiki/Magic_square
@goFrendiAsgard

**Comment by goFrendiAsgard** [comment]
Alasannya?

**Comment by bimprakosoo** [comment]
Saya sudah diskusi dengan temen temen tpi masih belum dapat solusi pak @goFrendiAsgard

**Comment by goFrendiAsgard** [comment]
@alola007 Coba konsul-kan dulu masalahnya ke ruangan saya, atau bisa ditulis di sini.

**Comment by bimprakosoo** [comment]
@goFrendiAsgard kalau nanti konsultasi jam 15.30 apa bisa pak ?

**Comment by goFrendiAsgard** [comment]
@alola007 bisa
